### ISSUE TITLE
migrate from exported file

### ISSUE THREAD

**Issue by cadsimula-xin** [tracboat/tracboat#27]
Hi,

the file is exported from trac instance as python format, while json format has utf8 issue like #6 

my migration configuration file

```
[tracboat]
from_export_file = "export_file.py"
fallback_user = "test@test.com"
gitlab_project_name = "testGroup/testProject"
gitlab_version = "8.9.11"
gitlab_db_user = "sagsdga"
gitlab_db_password = "gsagasgsadgas"
gitlab_db_path = "gitlab.example.com"
gitlab_uploads_path = "/tmp/gitlab/uploads/"

```

tracboat --config-file=migration.toml migrate
```
Traceback (most recent call last):
  File "/tmp/tracboat/tracboat/VENV/bin/tracboat", line 9, in <module>
    load_entry_point('tracboat==0.2.0a0', 'console_scripts', 'tracboat')()
  File "/tmp/tracboat/tracboat/src/tracboat/cli.py", line 423, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/tmp/tracboat/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tracboat/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tmp/tracboat/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/tracboat/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tracboat/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tracboat/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/tmp/tracboat/tracboat/src/tracboat/cli.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/tmp/tracboat/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/tracboat/tracboat/src/tracboat/cli.py", line 374, in migrate
    project = _loads(content, fmt=fmt)
  File "/tmp/tracboat/tracboat/src/tracboat/cli.py", line 72, in _loads
    return ast.literal_eval(content)
  File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python2.7/ast.py", line 63, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python2.7/ast.py", line 62, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python2.7/ast.py", line 63, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python2.7/ast.py", line 62, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python2.7/ast.py", line 63, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python2.7/ast.py", line 62, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string
```
Any suggestion is appreciated.

**Comment by glensc** [comment]
@cadsimula-xin i've reported (in some other issue, too lazy to find it now) similar thing and concluded that at current state export, use export file is not usable if you have binary attachments present.

so until then just use direct trac access.

**Comment by nazavode** [comment]
Hi @cadsimula-xin, @glensc is right, the binary encoding of blobs for `json` exports is actually broken (as reported in #13), sorry but in the past months I had so little time to work on this. This issue is top priority at the moment!

**Comment by nazavode** [comment]
@cadsimula-xin could you provide me the file causing this issue? I definitely need to set up a regression test for this. I'm looking for some base64 test data but no success up to now.

**Comment by crayfishuk** [comment]
I have this issue to and am happy to provide file - however it's not clear how I can determine which file/attachment is causing the issue. If you can provide pointers as to how I can find this out, I can provide...

**Comment by glensc** [comment]
@nazavode is no longer actively working on this project.

i suggest to use gitlab-direct only, the other serialization formats are incomplete.

**Comment by crayfishuk** [comment]
Cool. I know the docs state that the 10.5 db personality works with 10.6 and 10.7 - but how far does that go... 11? Will try it :-)

**Comment by glensc** [comment]
i've used 10.7 with 10.5 models.

ideally the schema pick up should be automatic and use ranges, i.e use 10.5 model for 10.5...10.8 as those are compatible.

there's some other issue open:
https://github.com/tracboat/tracboat/issues/19

**Comment by glensc** [comment]
if you can, you should wait when i have time to commit bulk of changes i've not published yet. mostly processing labels and markdown better.

**Comment by crayfishuk** [comment]
Ok.. will keep playin gin the meantime.  Have found issues with user creation (project_limits undefined) - but sidestepped by pre-creating users.  Have actually gone back to 10.5.8 to ensure that it's not a schema issue.

Also found some other issues with missing/unwriteable folders (wiki.export and rights to gitlab/uploads), and wiki_attachment encoding issues... 

Look forward to your changes :-)  

TIA

**Comment by glensc** [comment]
https://github.com/tracboat/tracboat/pull/48

currently it's export of my local changes with some changesets not suitable for publishing excluded. haven't tested the result yet.
