### ISSUE TITLE
user creation broken with 9.3 models

### ISSUE THREAD

**Issue by glensc** [tracboat/tracboat#34]
with 9.3 model (#33) i get error:

```
root@soa ~/tracboat# sudo -H -u git `which tracboat` --config-file=zave.toml migrate  --mock --mock-path=export/zave
Traceback (most recent call last):
  File "/home/glen/tracboat/VENV/bin/tracboat", line 9, in <module>
    load_entry_point('tracboat==0.2.0a0', 'console_scripts', 'tracboat')()
  File "/home/glen/tracboat/src/tracboat/cli.py", line 423, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/glen/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/glen/tracboat/src/tracboat/cli.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/glen/tracboat/src/tracboat/cli.py", line 413, in migrate
    userattrs=userattrs,
  File "/home/glen/tracboat/src/tracboat/migrate.py", line 344, in migrate
    output_uploads_path, create_missing=True)
  File "/home/glen/tracboat/src/tracboat/gitlab/direct.py", line 92, in __init__
    **NAMESPACE_DEFAULTS)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 4905, in create
    inst.save(force_insert=True)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 5098, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3516, in execute
    cursor = self._execute()
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 2902, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3765, in execute_sql
    self.commit()
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3588, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/glen/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 3758, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: namespaces.require_two_factor_authentication
(VENV)
```

i tried to patch this based on [documentation](https://docs.gitlab.com/ce/api/users.html#for-admins), but seems the values are different.

```
root@soa ~/tracboat# git diff
diff --git a/src/tracboat/migrate.py b/src/tracboat/migrate.py
index 28042b1..8b13316 100644
--- a/src/tracboat/migrate.py
+++ b/src/tracboat/migrate.py
@@ -349,7 +349,9 @@ def migrate(trac, gitlab_project_name, gitlab_version, gitlab_db_connector,
             'email': email,
             'username': email.split('@')[0],
             'encrypted_password': generate_password(),
+            'two_factor_enabled' : False,
         }
+
         attrs.update(userattrs.get(email, {}))
         gitlab.create_user(**attrs)
         LOG.info('created GitLab user %r', email)
(VENV)
```

imho creating users should be always done over rest API, never via direct models. as it's better maintained this way and doesn't need to know internals.

for creating tickets i understand the need for direct-api because rest api doesn't support "faking" date fields, etc. already suggested this: https://github.com/nazavode/tracboat/issues/21#issuecomment-296306448

**Comment by kerrhome** [comment]
You should really update the tracboat main page with this information (that user creation doesn't work).  I spent time trying to get what is there working only to find this ticket later on.  A note on the Readme.rst would have saved me a bunch of time. Just like note that the wiki step is commented out and the user just needs to uncomment it to enable it.

**Comment by glensc** [comment]
You are welcome to send your proposed readme update.

This kind of projects usually are fly-by by the people, as they get their projects converted and lose further interest.

I personally got over this problem somehow, I do not recall how. I think my flow is that I rely all users being present in target gitlab.

I'll close this specific issue, as I do not have the problem anymore.
