### ISSUE TITLE
create projects using rest-api not direct-api

### ISSUE THREAD

**Issue by glensc** [tracboat/tracboat#37]
(as pointed out earlier), creating users and now projects using directapi can cause gitlab to malfunction.

currently i got it broken because project was created so that some field is missing causing admin to crash:

```
==> /var/log/gitlab/gitlab-rails/production.log <==
Started GET "/admin" for 10.1.2.66 at 2017-08-07 16:01:05 +0300
Processing by Admin::DashboardController#index as HTML
Completed 500 Internal Server Error in 60ms (ActiveRecord: 6.8ms)

ActionView::Template::Error (undefined method `+' for nil:NilClass):
    161:             %h4 Latest projects
    162:             - @projects.each do |project|
    163:               %p
    164:                 = link_to project.name_with_namespace, [:admin, project.namespace.becomes(Namespace), project], class: 'str-truncated-60'
    165:                 %span.light.pull-right
    166:                   #{time_ago_with_tooltip(project.created_at)}
    167:       .col-md-4
  app/models/concerns/routable.rb:148:in `build_full_name'
  app/models/concerns/routable.rb:162:in `prepare_route'
  app/models/concerns/routable.rb:155:in `update_route'
  app/models/concerns/routable.rb:93:in `full_name'
  app/views/admin/dashboard/index.html.haml:164:in `block in _app_views_admin_dashboard_index_html_haml___3343335019850492670_69929727036400'
  app/views/admin/dashboard/index.html.haml:162:in `_app_views_admin_dashboard_index_html_haml___3343335019850492670_69929727036400'
  lib/gitlab/i18n.rb:45:in `with_locale'
  lib/gitlab/i18n.rb:51:in `with_user_locale'
  app/controllers/application_controller.rb:294:in `set_locale'
  lib/gitlab/performance_bar/peek_performance_bar_with_rack_body.rb:16:in `call'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'

```

**Comment by glensc** [comment]
for me it was able to create two projects with exactly same namespace and name:

```

irb(main):025:0> Project.find_each { |p| p.name_with_namespace rescue puts "#{p.id} #{p.namespace.name} #{p.name}\n" }
Scoped order and limit are ignored, it's forced to be batch order and batch size
189 group/subgroup projectname
190 group/subgroup projectname
=> nil
irb(main):026:0>
```

**Comment by glensc** [comment]
deleted invalid projects that tracboat has created (their `.path_with_namespace` throw error):

```
irb(main):038:0> Project.find_each { |p| p.name_with_namespace rescue p.delete }
Scoped order and limit are ignored, it's forced to be batch order and batch size
=> nil
irb(main):039:0>
```
