### ISSUE TITLE
11.4 Migration Issue.

### ISSUE THREAD

**Issue by ratherDashing** [tracboat/tracboat#54]
GitLab 11.4.5 (f5536c61210)

Properties file entires:

[tracboat]
trac_uri = "https://url/project/login/xmlrpc"
gitlab_project_name = "user/project"
gitlab_version = "11.0"
fallback_user = "me@domain.com"

Log Snippet

2018-11-14 17:26:40,318 DEBUG tracboat.trac: ticket_get_attachments of ticket #242
2018-11-14 17:26:41,415 DEBUG tracboat.trac: milestone_get_all
2018-11-14 17:26:41,416 DEBUG tracboat.trac: milestone_get_all_names
2018-11-14 17:26:52,860 DEBUG tracboat.trac: project_get is collecting authors from project
2018-11-14 17:26:52,862 INFO  migrate: migrating Trac project to GitLab
2018-11-14 17:26:52,862 INFO  migrate: Trac: https://url/project/login/xmlrpc
2018-11-14 17:26:52,862 INFO  migrate: GitLab project: user/project
2018-11-14 17:26:52,862 INFO  migrate: GitLab version: 11.0
2018-11-14 17:26:52,862 INFO  migrate: GitLab db path: /var/opt/gitlab/postgresql/
2018-11-14 17:26:52,862 INFO  migrate: GitLab db name: gitlabhq_production
2018-11-14 17:26:52,862 INFO  migrate: GitLab uploads: /var/opt/gitlab/gitlab-rails/uploads
2018-11-14 17:26:52,862 INFO  migrate: GitLab fallback user: me@domain.com
2018-11-14 17:26:52,862 INFO  tracboat.migrate: migrating project u'user/project' to GitLab ver. 11.0
2018-11-14 17:26:52,862 INFO  tracboat.migrate: uploads repository path is: '/var/opt/gitlab/gitlab-rails/uploads'
2018-11-14 17:26:52,920 INFO  tracboat.migrate: retrieved database model for GitLab ver. 11.0: '/home/ubuntu/tracboat/src/tracboat/gitlab/model/model110.pyc'
Traceback (most recent call last):
  File "/home/ubuntu/tracboat/VENV/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/home/ubuntu/tracboat/src/tracboat/cli.py", line 444, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/tracboat/src/tracboat/cli.py", line 134, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/tracboat/src/tracboat/cli.py", line 184, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/tracboat/src/tracboat/cli.py", line 434, in migrate
    svn2git_revisions=svn2git_revisions,
  File "/home/ubuntu/tracboat/src/tracboat/migrate.py", line 438, in migrate
    output_uploads_path, create_missing=False)
  File "/home/ubuntu/tracboat/src/tracboat/gitlab/direct.py", line 72, in __init__
    self.model.database_proxy.initialize(db_connector)
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 420, in initialize
    callback(obj)
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 1186, in _set_constructor
    self._constructor = database.get_binary_type()
  File "/home/ubuntu/tracboat/VENV/local/lib/python2.7/site-packages/peewee.py", line 4209, in get_binary_type
    return psycopg2.Binary
AttributeError: 'NoneType' object has no attribute 'Binary'

**Comment by tfpereira** [comment]
pip install psycopg2-binary
