### ISSUE TITLE
Migrating Trac 1.2 to Gitlab 11.5.0

### ISSUE THREAD

**Issue by benshanahan1** [tracboat/tracboat#56]
I am currently trying to migrate Trac 1.2 to GitLab 11.5.0. GitLab is running on Ubuntu 18.04.1 LTS x86_64. Per the README notes, I've tried migrating with `gitlab_version` set to 11.0. The README also mentioned that any issues encountered with the migration process should be opened here.

My 'migrate.toml' file:
```toml
[tracboat]
trac_uri = "https://user:pass@trac.example.com/rpc"
ssl_verify = false
gitlab_project_name = "migrated/tracwiki"
fallback_user = "ben@example.com"
gitlab_version = "11.0"
```

I am running this in my terminal:
```bash
tracboat --config-file migrate.toml migrate
```

I am getting the following error:
```text
Traceback (most recent call last):
  File "/home/ben/code/tracboat/VENV/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/home/ben/code/tracboat/src/tracboat/cli.py", line 428, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/ben/code/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ben/code/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ben/code/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ben/code/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ben/code/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ben/code/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/ben/code/tracboat/src/tracboat/cli.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/ben/code/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ben/code/tracboat/src/tracboat/cli.py", line 418, in migrate
    svn2git_revisions=svn2git_revisions,
  File "/home/ben/code/tracboat/src/tracboat/migrate.py", line 449, in migrate
    gitlab.clear_issues()
  File "/home/ben/code/tracboat/src/tracboat/gitlab/direct.py", line 140, in clear_issues
    for issue in M.Issues.select().where(M.Issues.project == self.project_id):
  File "/home/ben/code/tracboat/src/tracboat/gitlab/__init__.py", line 53, in project_id
    self._project_id = self._get_project_id()
  File "/home/ben/code/tracboat/src/tracboat/gitlab/direct.py", line 109, in _get_project_id
    raise ValueError("Project {!r} not found".format(self.project_qualname))
ValueError: Project u'migrated/tracwiki' not found
```

Any advice is greatly appreciated. Cheers!

**Comment by kerrhome** [comment]
Did you ever figure this out @benshanahan1 ?

**Comment by benshanahan1** [comment]
Not yet, unfortunately.

**Comment by glensc** [comment]
from my local testing, 11.0 model is ok for 11.6, 11.7, 11.8.

altho I don't migrate wikis (commented out that part in code).

is group `migrated` present in your gitlab? try importing to existing group (or user)

so, the suggestion is to add debugging to tracboat code.

**Comment by benshanahan1** [comment]
I am no actively working to migrate the old Trac instance to GitLab, but thank you for testing which models are compatible. Closing the issue.
