### ISSUE TITLE
OOM during migrate

### ISSUE THREAD

**Issue by kerrhome** [tracboat/tracboat#62]
I'm running out of system memory during tracboat migrate (when migrating with attachments).  Anyone else ever experience this?  Is there a way to break up the import so I can complete it with the memory I have?  Other suggestions?

```
root@gitlab:/var/opt/gitlab/temp/tracboat# ./tracboat.sh -vv --config-file=mytrac.toml migrate 2>&1 | tee log_newJ
2019-03-07 22:27:07,656 DEBUG migrate: usermap is: {}
2019-03-07 22:27:07,656 DEBUG migrate: default user attributes are: {}
2019-03-07 22:27:07,656 DEBUG migrate: user attributes is: defaultdict(<function <lambda> at 0x7fcf7ea10848>, {})
2019-03-07 22:27:07,656 INFO  migrate: loading Trac instance from export file: new_repo.json
2019-03-07 22:27:07,656 DEBUG migrate: detected file format: json
Traceback (most recent call last):
  File "/var/opt/gitlab/temp/tracboat/VENV/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 428, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 377, in migrate
    content = export_f.read()
  File "/var/opt/gitlab/temp/tracboat/VENV/lib/python2.7/codecs.py", line 686, in read
    return self.reader.read(size)
  File "/var/opt/gitlab/temp/tracboat/VENV/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
MemoryError
```

**Comment by kerrhome** [comment]
To get past the OOM issue, we made the following change:
```
diff --git a/src/tracboat/cli.py b/src/tracboat/cli.py
index c45c606..eff91a8 100644
--- a/src/tracboat/cli.py
+++ b/src/tracboat/cli.py
@@ -373,9 +373,10 @@ def migrate(ctx, umap, umap_file, fallback_user, trac_uri, ssl_verify,
         LOG.info('loading Trac instance from export file: %s', from_export_file)
         fmt = _detect_format(from_export_file)
         LOG.debug('detected file format: %s', fmt)
-        with codecs.open(from_export_file, 'rb', encoding='utf-8') as export_f:
-            content = export_f.read()
-        project = _loads(content, fmt=fmt)
+        #with codecs.open(from_export_file, 'rb', encoding='utf-8') as export_f:
+        #    content = export_f.read()
+        #project = _loads(content, fmt=fmt)
+        project = pickle.load(open(from_export_file))
     else:
```

**Comment by jschewebbn** [comment]
Even with this change we are running out of memory. Any other suggestions on getting passed this?

**Comment by jschewebbn** [comment]
In the end I got around this by exporting directly to a pickle file rather than converting to pickle in memory and then writing. I did the same on the import side.
