### ISSUE TITLE
problems with attachments and encoding

### ISSUE THREAD

**Issue by bwl21** [tracboat/tracboat#63]
Thanks for tracboat - it gives me hope to migrate sucessfully from trac to gitlab.

I have problems to read the attachments from the trac instance. 

with python:3.4 I get several messages like this. I assume it is one per attachment.

```
2019-03-08 13:47:49,730 ERROR tracboat.trac: error while decoding data from base64
Traceback (most recent call last):
  File "/src/tracboat/trac.py", line 15, in _safe_retrieve_data
    return six.b(data)
  File "/usr/local/lib/python3.4/site-packages/six.py", line 620, in b
    return s.encode("latin-1")
AttributeError: 'bytes' object has no attribute 'encode'
```

when I use python:2.7 i get

```
Traceback (most recent call last):
  File "/usr/local/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/src/tracboat/cli.py", line 428, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/src/tracboat/cli.py", line 268, in export
    project = _dumps(project, fmt=format)
  File "/src/tracboat/cli.py", line 44, in _dumps
    return json.dumps(obj, sort_keys=True, indent=2, default=json_util.default)
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte

```

**Comment by kerrhome** [comment]
I'll bet this is a duplicate of ticket #6.  There is a potential solution for this at the bottom of that ticket.  I'm working through this at my site as well and I *think* I got that code to work, but now I'm running out of memory on the import.

**Comment by bwl21** [comment]
I guess you run out of memory if you have many attachments. I have only 42 :-)

I don't know python at all. Which files did you change? I could try with my setup, maybe it works.

**Comment by kerrhome** [comment]
The change I made is the last comment of ticket #6.  Make that change to that file and you may be good.  No promises as I'm still trying to figure out if it is good.  We have been able to work around the OOM issue and now we've got encoding issues with the first ticket that had a binary attachment.

**Comment by glensc** [comment]
> The change I made is the last comment of ticket #6.

link to the specific comment (click on comment date), the "last comment" is variable result depending on when you look a the page :)

as for the fixes, submit PR so the other users can apply it for testing.

**Comment by kerrhome** [comment]
:) Sorry, @glensc is correct.  Here is the change I was talking about: 
https://github.com/tracboat/tracboat/issues/6#issuecomment-394353933

**Comment by kerrhome** [comment]
I will submit a PR once we have binary attachments uploading.  We're having to tweak that solution I linked to.

**Comment by bwl21** [comment]
I have installed ftfy but I had to nail it to 4.4.3 as I work with python 2.7.  3.4. makes different messages so I decide do focus on 2.7 which at least produces a json file ...

    The older version of ftfy, version 4.4, is still available and can run on
    Python 2. Try this:
    
        pip install ftfy==4.4.3

If I fix this in requirements/dist.txt it get a valid json file. I wonder if  it eventually can be imported to gitlab.

The attachment data look like this

```json
          "data": "\ufffd\ufffd\ufffd\ufffd\u0000\u0010JFIF\u0000\u0001\u0001\u0000\
```

**Comment by kerrhome** [comment]
Yeah, we did all of that too and got to where you are now.  The `fffd`'s are bad translations.  To fix this, we had to change the way we dump binary files.  We have a full pickle dump of our repo with attachments that we keep working with.  Here is what we're running on that dump to get the binary files to convert from our full pickle dump:

```
#python2
import pickle
import json
from bson import json_util
import codecs
from ftfy import fix_encoding
import collections

def convert(data):
    # Using Python2 str/unicode difference (WILL NOT WORK with Python3! str is always unicode and basestring disappeared)
    if isinstance(data, str):
        try:
            return data.decode('utf-8')
        except UnicodeDecodeError:
            pass
    elif isinstance(data, unicode):
        return fix_encoding(data)
    elif isinstance(data, collections.Mapping):
        return dict(map(convert, data.iteritems()))
    elif isinstance(data, collections.Iterable):
        return type(data)(map(convert, data))
    return data

print("importing")
x = pickle.load(open("pickle_dump.p"))

print("converting")
x = convert(x)

print("dumping")
pickle.dump(x, open('new_DVR.pickle', 'w'), pickle.HIGHEST_PROTOCOL)
```

This is absolutely working. I have successfully imported binary files (just tested .doc files so far) into GitLab and then downloaded them to my system to verify they are working properly.

**Comment by bwl21** [comment]
My problem is that the trac server will be switched of in the next hours, and I have to pull out of it whatever I can ... Therefore I concentrate to get a json fie. Which I can process later.
Just to be safe, I also have a mysqldump from the trac server and the attachments as file. I managed to setup a trac in a docker container with tracd. But with tracd xmlrpc does not work. 

I have absolutely no experience with python ... did not even know, what a pickle dump is.

how do you create that dump?

Nevertheless

I am running a gitlab instance in a docker container. Now I have no clue how I can import that stuff to gitlab, as I am running it with mysql. Can you help me with this?

**Comment by kerrhome** [comment]
There is a pickle format option to tracboat that dumps it as a .pickle file instead of .json file.

We are also running gitlab in a docker container. I setup persistent volumes and I'm just copying the dump files into the persistent gitlab_data volume and then running tracboat migrate from within the docker container.  So `docker exec -it gitlab bash` to get into the container, `cd /var/opt/gitlab` and there I created a temp directory.  Then I did a "git clone" of tracboat and went to work with the migrate step.  I was doing the rest of my work from the docker host, not the gitlab container.

**Comment by bwl21** [comment]
I have created a Dockerfile for tracboat and plan to link it with the same mysql service used by gitlab. 
But I do not see how I can tell tracboat to use mysql instead lf postgres.

At the moment I am trying to do the import with mock=true. But I stumble from problem to problem ...

**Comment by kerrhome** [comment]
Yeah, we're using Dockerfile too, but stuck with postgres.   Can't say about the tracboat config for using mysql.

**Comment by bwl21** [comment]
even with mock i get

```
  File "/src/tracboat/users.py", line 61, in create_user
    attrs.update(userattrs.get(email, {}))
NameError: global name 'userattrs' is not defined
```

Creation of user is hardcoded turned off. But If I import in an empt database, I need to create the users. So I turned this on .

**Comment by bwl21** [comment]
I tried to export pickle format:

```
  File "/usr/local/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 855: ordinal not in range(128)
```

**Comment by kerrhome** [comment]
Yeah, we are rapidly fixing stuff as we go here and I'm afraid I am not tracking all of the details.  We skipped the cli.py export() `out_f.write(project)` and just added the following to the json block (yes, the json block) in _dumps():
```
pickle.dump(obj, open("dump.pickle","wb"), pickle.HIGHEST_PROTOCOL)
```

That got us our pickle dump, which we've used for all subsequent work.

Here is the diff:
```
@@ -41,6 +42,8 @@ def _dumps(obj, fmt=None):
     if fmt == 'toml':
         return toml.dumps(obj)
     elif fmt == 'json':
+        print("Running pickle.dump on obj\n")
+        pickle.dump(obj, open("dump.pickle","wb"), pickle.HIGHEST_PROTOCOL)
         return json.dumps(obj, sort_keys=True, indent=2, default=json_util.default)
     elif fmt == 'python':
         return pformat(obj, indent=2)
```

**Comment by bwl21** [comment]
@kerrhome 

> Yeah, we're using Dockerfile too, but stuck with postgres. Can't say about the tracboat config for using mysql.

Sorry, I was messed up. I am using gitlab/gitlab-ce:latest which indeed works with postres.

As a pity, the trac server is no longer available, so I could not try the pickle export again. my first attempt failed as I wrote in the comment before. https://github.com/tracboat/tracboat/issues/63#issuecomment-471013827

So next I need to setup a trac instance with apache in my docker to have another chance to do the export.

But even with the json files, I do not manage to run the import. 

I created a docker compose to start all the necessary containers:

````docker-compose
  tracboat:
    build: tracboat
    image: bwl21/tracboat
    restart: always
    container_name: tracboat
    volumes:
      - .:/usr/src/myapp
      - /Users/beweiche/gitlab/data:/var/opt/gitlab

  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - 443:443
      - 80:80
      - 22:22
    container_name: gitlab

    restart: unless-stopped
    volumes:
     - /Users/beweiche/gitlab/config:/etc/gitlab
     - /Users/beweiche/gitlab/logs:/var/log/gitlab
     - /Users/beweiche/gitlab/data:/var/opt/gitlab
```

> So`docker exec -it gitlab bash` to get into the container, `cd /var/opt/gitlab` and there I created a temp directory. Then I did a "git clone" of tracboat and went to work with the migrate step. I was doing the rest of my work from the docker host, not the gitlab container.

Does that mean that you are using tracboat on the host level? I have also crated a docker container for tracboat:

```Dockerfile
FROM python:2.7

#todo: do not copy stuff to root
COPY requirements/dist.txt .
COPY setup.py .
COPY README.rst .
COPY src src/

RUN   pip install -r dist.txt && \
      pip install -e .

ENTRYPOINT bash
```

and start it with 
```
docker-compose up gitlab
docker-compose run -rm tracboat
```
which then should allow me to do  the migration within tracboat.

I try `tracboat --config-file=toml/push-to-gitlab.toml migrate`

with toml/push-to-gitlab.toml as

```
[tracboat]
from_export_file = "tracboat-json-files/pjtadmin_with_attachments.json"
gitlab_project_name = "bwl21/pjtadmin"
# see below to choose the right version
gitlab_version = "11.0"
gitlab_user = "root"
gitlab_password = "password"
gitlab_db_password = "Բարեւ աշխարհ"
# gitlab_db_user = "gitlab"
gitlab_db_path = "/var/opt/gitlab/postgresql/"
```

I could not find out where the db_password Բարեւ աշխարհ is defined ... it must be somewhere in the gitlab/postgres defaults

it ends in a message

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

Now I am stuck. I cannot see a way how to get the stuff in pickle format ...

any idea is highly welcome ...

**Comment by kerrhome** [comment]
We did not have as much with json as we did with pickle, so I can't say, but maybe @glensc can help.  We did encounter the UnicodeEncodeError messages like those with both json and pickle and this comment should help with some of that: 
https://github.com/tracboat/tracboat/issues/63#issuecomment-470997932

My hope is that I can create a branch with all of our various fixes in it to give back to this project, but right now I'm focused on getting our teams up and running.  Now I'm focused on updates to https://github.com/tracboat/tracboat/blob/master/src/tracboat/trac2down.py to improve our wiki conversion.

When you run migrate,  you need to run it in the docker container running gitlab as it needs to communicate with the gitlab db.  No documentation tells you this, unfortunately, but hopefully this helps you.  I ran `git clone <tracboat>` to get the tracboat tools in my gitlab docker container and then pulled the pickle dump to that container to run the migrate step as root because the tracboat.sh script will use sudo to set the user as "git".  You will need to `apt update && apt install -y sudo python python-pip` in the gitlab docker container in order to run the tracboat tools.

**Comment by kerrhome** [comment]
btw, the DB password is whatever the password was when you setup the GitLab "root" account.  Also was not documented. :( 

You do not need to set gitlab_user or gitlab_user_password.  Just set the gitlab_db_password to the root account password.  If you are transitioning the wiki, the instructions for that are not documented, but I can help with that as we did finally figure out that it is commented out by default and traced through the code to figure out how it is actually done (which was a great mystery for a while).

**Comment by bwl21** [comment]
Thanks for your reply.

I changed my tracboat docker file to 

```

FROM python:2.7

RUN apt update && apt install -y sudo python python-pip

WORKDIR /usr/tracboat

COPY requirements/dist.txt setup.py README.rst ./
COPY src src/

RUN   pip install -r dist.txt && \
      pip install -e .

WORKDIR /usr/src/myapp

VOLUME /var/opt/gitlab

ENTRYPOINT /bin/bash
```
It did not work better. Now the origin trac server is turned off, so I only have the chance to read the trac data from mysql. So I have to give up this path.


Meanwhile, I was much more successful with https://github.com/mavam/trac-hub. It is Ruby (which i know well) and imported our stuff to github on the first shot. I even found out how to tweak this importer. So for the time being, I follow this track. I have to make my team going this week ...

Nevertheless I monitor tracboat to see your contributions. There is another project hanging around, which I will have to migrate which would be a new game.

**Comment by kerrhome** [comment]
I'm glad you made progress.  I have a fork of tracboat under kerrhome/tracboat, but I won't be updating it for a bit.  I pulled that fork to my local gitlab instance where I'll work on it for now.

**Comment by kerrhome** [comment]
btw, now that you have your content in GitHub, you can easily pull your project from GitHub into GitLab if you still want to go with GitLab.  There excellent project import functionality built into GitLab that easily pulls any projects you own from GitHub into GitLab.

**Comment by bwl21** [comment]
Exactly this is the plan. By this approach I even have the choice between github and gitlab. And as github now provides private repositories it is a good path.
