### ISSUE TITLE
wiki migration "file already exists"

### ISSUE THREAD

**Issue by kerrhome** [tracboat/tracboat#64]
It took me a bit, but I did finally figure out that the wiki step is actually commented out in migration.py.  Maybe this could be a command line option instead of just commenting it out? Or at least perhaps a comment on README.rst would help.

I did get pretty far in my wiki migration step, but failed because of a duplicate filename:
```
....
2019-03-08 19:29:33,887 DEBUG tracboat.migrate: migrated attachment TestResults-s7dvr-7.5.0.35184 @ TestResults-s7dvr-7.5.0.35184/EncoderResults.htm
......
Traceback (most recent call last):
  File "/var/opt/gitlab/temp/tracboat/VENV/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 429, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/cli.py", line 419, in migrate
    svn2git_revisions=svn2git_revisions,
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/migrate.py", line 454, in migrate
    migrate_wiki(trac['wiki'], gitlab, output_wiki_path)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/migrate.py", line 406, in migrate_wiki
    gitlab.save_attachment(name, data)
  File "/var/opt/gitlab/temp/tracboat/src/tracboat/gitlab/direct.py", line 369, in save_attachment
    raise Exception("file already exists: %r" % filename)
Exception: file already exists: u'/var/opt/gitlab/gitlab-rails/uploads/exacq/DVRtemp/EncoderResults.htm'
```

So there was an import of EncoderResults.htm directly to `/var/opt/gitlab/gitlab-rails/uploads/exacq/DVRtemp`, but that was from the wiki page `TestResults-s7dvr-7.5.0.35184`.  There is another wiki page named `TestResults-s7dvr-7.5.0.33815` that also has a EncoderResults.htm.

How should this be handled?

**Comment by kerrhome** [comment]
Looking at the code, the wiki attachments are dumped into the common uploads directory for DVRtemp, so there is not much I can do about this with the existing structure.  It will just not allow for two files in the same Trac wiki to have the same name.
