### ISSUE TITLE
Export fails if attachments can't be found

### ISSUE THREAD

**Issue by don-vip** [tracboat/tracboat#69]
Export fails if attachments can't be found, I would instead expect a warning?

```
(VENV) josm@josm:~$ tracboat export --trac-uri=$TRACBOAT_TRAC_URI --format=json --out-file=/home/josm/team/Vincent/josm_trac_export_20190504_1924.json
/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/home/josm/tracboat/VENV/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/home/josm/tracboat/src/tracboat/cli.py", line 428, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/josm/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/josm/tracboat/VENV/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/josm/tracboat/src/tracboat/cli.py", line 267, in export
    project = trac.project_get(source, collect_authors=True)
  File "/home/josm/tracboat/src/tracboat/trac.py", line 142, in project_get
    'tickets': ticket_get_all(source),
  File "/home/josm/tracboat/src/tracboat/trac.py", line 81, in ticket_get_all
    for ticket_id in source.ticket.query("max=0&order=id")
  File "/home/josm/tracboat/src/tracboat/trac.py", line 81, in <dictcomp>
    for ticket_id in source.ticket.query("max=0&order=id")
  File "/home/josm/tracboat/src/tracboat/trac.py", line 69, in ticket_get_attachments
    for meta in source.ticket.listAttachments(ticket_id)
  File "/home/josm/tracboat/src/tracboat/trac.py", line 69, in <dictcomp>
    for meta in source.ticket.listAttachments(ticket_id)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 404: "Attachment '6964_validator_init_quickfix.patch' not found">
```

In this case it seems we have indeed a database corruption:
* https://josm.openstreetmap.de/ticket/6964#no1
* https://josm.openstreetmap.de/attachment/ticket/6964/6964_validator_init_quickfix.patch

**Comment by don-vip** [comment]
To workaround this issue, we've now deleted the missing attachment from our trac database.
