### ISSUE TITLE
12.x support?

### ISSUE THREAD

**Issue by anarcat** [tracboat/tracboat#72]
are 12.x models supported?

**Comment by glensc** [comment]
last model could work, but not tested:
- https://github.com/tracboat/tracboat#gitlab-version-compatibility

**Comment by jsaathof** [comment]
Got an error which leads me to believe that the database schema in Gitlab 12 has changed.

```
Traceback (most recent call last):
  File "/root/tracboat/VENV/bin/tracboat", line 11, in <module>
    load_entry_point('tracboat', 'console_scripts', 'tracboat')()
  File "/root/tracboat/src/tracboat/cli.py", line 428, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
  File "/root/tracboat/VENV/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/tracboat/VENV/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/tracboat/src/tracboat/cli.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/root/tracboat/src/tracboat/cli.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/tracboat/src/tracboat/cli.py", line 418, in migrate
    svn2git_revisions=svn2git_revisions,
  File "/root/tracboat/src/tracboat/migrate.py", line 441, in migrate
    gitlab.clear_issues()
  File "/root/tracboat/src/tracboat/gitlab/direct.py", line 146, in clear_issues
    for issue in M.Issues.select().where(M.Issues.project == self.project_id):
  File "/root/tracboat/src/tracboat/gitlab/__init__.py", line 53, in project_id
    self._project_id = self._get_project_id()
  File "/root/tracboat/src/tracboat/gitlab/direct.py", line 107, in _get_project_id
    project = self._get_project(self.project_name, self.project_namespace)
  File "/root/tracboat/src/tracboat/gitlab/direct.py", line 120, in _get_project
    (M.Namespaces.path == p_namespace)).get()
  File "/root/tracboat/VENV/lib/python2.7/site-packages/peewee.py", line 3171, in get
    return next(clone.execute())
  File "/root/tracboat/VENV/lib/python2.7/site-packages/peewee.py", line 3223, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/peewee.py", line 2902, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/peewee.py", line 3765, in execute_sql
    self.commit()
  File "/root/tracboat/VENV/lib/python2.7/site-packages/peewee.py", line 3588, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/root/tracboat/VENV/lib/python2.7/site-packages/peewee.py", line 3758, in execute_sql
    cursor.execute(sql, params or ())
peewee.ProgrammingError: column t1.ci_id does not exist
LINE 1: ..."cached_markdown_version", "t1"."ci_config_path", "t1"."ci_i...
```
