### ISSUE TITLE
cant export users from trac 1.2.6 , 

### ISSUE THREAD

**Issue by ansvcholayi** [tracboat/tracboat#83]
config.toml

```
[tracboat]
trac_uri = "https://username:password@sjodktrac1.ansys.com/rpc"
ssl_verify = false
```

```
D:\tracboat>tracboat --config-file="D:\tracboat\examples\config.toml" users
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\tracboat.exe\__main__.py", line 7, in <module>
  File "D:\tracboat\src\tracboat\cli.py", line 428, in main
    cli(obj={})  # pylint: disable=unexpected-keyword-arg,no-value-for-parameter
    ^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tracboat\src\tracboat\cli.py", line 118, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tracboat\src\tracboat\cli.py", line 240, in users
    authors = trac.authors_get(source)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tracboat\src\tracboat\trac.py", line 169, in authors_get
    wiki = wiki_get_all_pages(source, contents=False, attachments=False) if from_wiki else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tracboat\src\tracboat\trac.py", line 132, in wiki_get_all_pages
    for name in source.wiki.getAllPages()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\xmlrpc\client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\xmlrpc\client.py", line 1461, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\xmlrpc\client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\xmlrpc\client.py", line 1178, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\xmlrpc\client.py", line 1291, in send_request
    self.send_content(connection, request_body)
  File "C:\Python312\Lib\xmlrpc\client.py", line 1321, in send_content
    connection.endheaders(request_body)
  File "C:\Python312\Lib\http\client.py", line 1314, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python312\Lib\http\client.py", line 1074, in _send_output
    self.send(msg)
  File "C:\Python312\Lib\http\client.py", line 1018, in send
    self.connect()
  File "C:\Python312\Lib\http\client.py", line 1453, in connect
    super().connect()
  File "C:\Python312\Lib\http\client.py", line 984, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\socket.py", line 852, in create_connection
    raise exceptions[0]
  File "C:\Python312\Lib\socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by glensc** [comment]
> ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

looks like there's no webserver at the configured address. try connecting there with other tools, curl, telnet, netcat to confirm connection can be made.
